# Generated by Django 4.2.30 on 2026-09-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('prioridad', models.IntegerField(default=1)),
                ('recompensa_puntos', models.IntegerField(default=1)),
            ],
        ),
    ]
