# Generated by Django 4.2.30 on 2026-09-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='numero_pergamino',
            field=models.IntegerField(choices=[(1, 'Pergamino 1'), (2, 'Pergamino 2'), (3, 'Pergamino 3'), (4, 'Pergamino 4'), (5, 'Pergamino 5'), (6, 'Pergamino 6')], default=1, verbose_name='Número de Pergamino (PNG)'),
        ),
        migrations.AddField(
            model_name='mision',
            name='rol_permitido',
            field=models.CharField(choices=[('dibujante', 'Dibujante'), ('hibrido', 'Híbrido'), ('escritor', 'Escritor'), ('cualquiera', 'Cualquiera')], default='cualquiera', max_length=30, verbose_name='Rol Permitido'),
        ),
        migrations.AddField(
            model_name='mision',
            name='tipo_mision',
            field=models.CharField(choices=[('principal', 'Misión Principal'), ('secundaria', 'Misión Secundaria'), ('diaria', 'Misión Diaria')], default='secundaria', max_length=20, verbose_name='Tipo de Misión'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='prioridad',
            field=models.IntegerField(default=1, verbose_name='Prioridad (Estrellas)'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='recompensa_puntos',
            field=models.IntegerField(default=1, verbose_name='Recompensa Puntos'),
        ),
    ]
