# Generated by Django 4.2.30 on 2026-09-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0002_mision_numero_pergamino_mision_rol_permitido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol Permitido',
                'verbose_name_plural': 'Roles Permitidos',
            },
        ),
        migrations.RemoveField(
            model_name='mision',
            name='rol_permitido',
        ),
        migrations.RemoveField(
            model_name='mision',
            name='tipo_mision',
        ),
        migrations.AddField(
            model_name='mision',
            name='categoria',
            field=models.CharField(choices=[('creador_personaje', 'Creador de personaje'), ('creacion_lore', 'Creación de lore'), ('juegos_casino', 'Juegos de casino'), ('mecanicas_jugador', 'Mecánicas del jugador'), ('npc', 'Npc'), ('creacion_mapa', 'Creación del mapa'), ('rogue_lite', 'Rogue Lite')], default='creador_personaje', max_length=30, verbose_name='Categoría de Misión'),
        ),
        migrations.AddField(
            model_name='mision',
            name='roles_permitidos',
            field=models.ManyToManyField(blank=True, to='nucleo.rol', verbose_name='Roles Permitidos'),
        ),
    ]
