# Generated by Django 4.2.30 on 2026-09-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0003_rol_remove_mision_rol_permitido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mision',
            name='roles_permitidos',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.AddField(
            model_name='mision',
            name='roles_permitidos',
            field=models.CharField(default=1, help_text='Mantén presionado Ctrl (o Cmd en Mac) para seleccionar más de un rol.', max_length=200, verbose_name='Roles Permitidos'),
            preserve_default=False,
        ),
    ]
