# Generated by Django 4.2.30 on 2026-09-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0004_remove_mision_roles_permitidos_delete_rol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mision',
            name='asignado_a',
            field=models.CharField(choices=[('kano', 'Kano'), ('ruoye', 'Ruoye'), ('vicho', 'Vicho'), ('lea', 'Lea'), ('kaiser', 'Kaiser'), ('walalan', 'Walalan'), ('hisoka', 'Hisoka'), ('todos', 'Todos / Libre')], default='todos', max_length=30, verbose_name='Asignado a'),
        ),
        migrations.AddField(
            model_name='mision',
            name='estado',
            field=models.CharField(choices=[('disponible', '⚔️ Disponible en Tablero'), ('en_progreso', '⏳ En Progreso (Tomada)'), ('completada', '💎 Completada y Entregada')], default='disponible', max_length=20, verbose_name='Estado de la Misión'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='roles_permitidos',
            field=models.CharField(default='', help_text='Mantén presionado Ctrl para seleccionar más de un rol.', max_length=200, verbose_name='Roles Permitidos'),
        ),
    ]
