# Generated by Django 4.2.30 on 2026-09-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleo', '0005_mision_asignado_a_mision_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaPendiente',
            fields=[
            ],
            options={
                'verbose_name': 'Entrega pendiente',
                'verbose_name_plural': 'Entregas pendientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nucleo.mision',),
        ),
        migrations.CreateModel(
            name='MisionCompletada',
            fields=[
            ],
            options={
                'verbose_name': 'Misión completada',
                'verbose_name_plural': 'Baúl de misiones completadas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('nucleo.mision',),
        ),
        migrations.AddField(
            model_name='mision',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='mision',
            name='fecha_entregada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='mision',
            name='fecha_tomada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha en que se tomó'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='estado',
            field=models.CharField(choices=[('disponible', '⚔️ Disponible en Tablero'), ('en_progreso', '⏳ En Progreso (Tomada)'), ('entregada', '📨 Pendiente de Revisión'), ('completada', '💎 Completada')], default='disponible', max_length=20, verbose_name='Estado de la Misión'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='recompensa_puntos',
            field=models.IntegerField(default=1, verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='mision',
            name='roles_permitidos',
            field=models.CharField(default='', max_length=200, verbose_name='Roles Permitidos'),
        ),
    ]
